// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
const config = {
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
};
if (process.env["DATABASE_URL"]) {
    config.datasource = {
        url: process.env["DATABASE_URL"],
    };
}
export default defineConfig(config);
//# sourceMappingURL=prisma.config.js.map